language: go
go:
  - 1.15.6
  - tip
matrix:
  allow_failures:
    - go: tip

notifications:
  email:
    recipients: dean.karn@gmail.com
    on_success: change
    on_failure: always

before_install:
  - go get -u github.com/mattn/goveralls

before_script:
  - go mod download

script:
  - make lint
  - make test

after_success: |
  [ $TRAVIS_GO_VERSION = 1.15.6 ] &&
  go test ./... -covermode=count -coverprofile=coverage.out &&
  goveralls -coverprofile=coverage.out -service travis-ci -repotoken $COVERALLS_TOKEN
